spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

server:
  port: 8081

kafka:
  topics:
    payment-result: payment.result.v1
    order-paid: order.paid.v1
    delivery-completed: delivery.completed.v1