apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: allmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 646596232446.dkr.ecr.ap-northeast-2.amazonaws.com/order-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "43.203.213.93:19092,43.203.213.93:19093,43.203.213.93:19094"
            - name: REDIS_SENTINEL_NODES
              value: "43.203.213.93:26379,43.203.213.93:26380,43.203.213.93:26381"
            - name: REDIS_MASTER_NAME
              value: "mymaster"
            - name: DB_HOST
              value: "52.78.67.189"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "order"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: password
            - name: TEMPO_ENDPOINT
              value: "http://43.200.2.221:4318/v1/traces"
            - name: LOKI_URL
              value: "http://43.200.2.221:3100/loki/api/v1/push"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: allmart
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081
